name: release
on:
  # workflow_dispatch:
  #   inputs:
  #     releaseType:
  #       description: "Release Type"
  #       required: true
  #       type: choice
  #       default: "patch"
  #       options:
  #         - patch
  #         - minor
  #         - major
  #     releaseChannel:
  #       description: "Release Channel"
  #       required: true
  #       type: choice
  #       default: stable
  #       options:
  #         - stable
  #         - edge
  #     publishMarketplace:
  #       description: "Publish on Visual Studio Marketplace?"
  #       required: true
  #       type: choice
  #       default: "yes"
  #       options:
  #         - "yes"
  #         - "no"
  #     publishOpenVSX:
  #       description: "Publish on Open VSX Registry?"
  #       required: true
  #       type: choice
  #       default: "yes"
  #       options:
  #         - "yes"
  #         - "no"
  push:
    branches: [main]
  release:
    types:
    - created
jobs:
  code:
    uses: unional/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      node-version: '[20]'

  release:
    runs-on: ubuntu-latest
    needs: code
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_GITHUB_TOKEN }}
    - uses: pnpm/action-setup@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
    - run: pnpm install
    - run: pnpm esbuild-base --minify
    - name: Publish
      # if: success() && startsWith(github.ref, 'refs/tags/')
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
  # docgen:
  #     uses: unional/.github/.github/workflows/pnpm-docs.yml@main
  #     needs: release
