name: release
on:
  # workflow_dispatch:
  #   inputs:
  #     releaseType:
  #       description: "Release Type"
  #       required: true
  #       type: choice
  #       default: "patch"
  #       options:
  #         - patch
  #         - minor
  #         - major
  #     releaseChannel:
  #       description: "Release Channel"
  #       required: true
  #       type: choice
  #       default: stable
  #       options:
  #         - stable
  #         - edge
  #     publishMarketplace:
  #       description: "Publish on Visual Studio Marketplace?"
  #       required: true
  #       type: choice
  #       default: "yes"
  #       options:
  #         - "yes"
  #         - "no"
  #     publishOpenVSX:
  #       description: "Publish on Open VSX Registry?"
  #       required: true
  #       type: choice
  #       default: "yes"
  #       options:
  #         - "yes"
  #         - "no"
  push:
    branches: [main]

jobs:
  code:
    uses: unional/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      node-version: '[18]'


  # release:
  #   uses: unional/.github/.github/workflows/pnpm-release-changeset.yml@main
  #   needs: code
  #   secrets: inherit

  # docgen:
  #     uses: unional/.github/.github/workflows/pnpm-docs.yml@main
  #     needs: release
